spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms
    username: ilqar
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
